// Narrates the read-along passage with the app's own Kokoro script and writes the audio plus the
// word cues the reader highlights from. Needs a libratory checkout with its Python env set up:
//
//   LIBRATORY_DIR=~/repos/libratory node scripts/narrate.mjs
//
import { execFile } from "node:child_process";
import { mkdtemp, readFile, readdir, writeFile } from "node:fs/promises";
import { homedir, tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";

const run = promisify(execFile);

const REPO = process.env.LIBRATORY_DIR ?? join(homedir(), "repos/libratory");
const VOICE = process.env.VOICE ?? "af_heart";
const AUDIO = `public/audio/frankenstein-ch5-${VOICE}.m4a`;
const CUES = "src/components/cues.ts";

const SENTENCES = [
  "It was on a dreary night of November that I beheld the accomplishment of my toils.",
  "With an anxiety that almost amounted to agony, I collected the instruments of life around me, that I might infuse a spark of being into the lifeless thing that lay at my feet.",
  "It was already one in the morning; the rain pattered dismally against the panes, and my candle was nearly burnt out, when, by the glimmer of the half-extinguished light, I saw the dull yellow eye of the creature open.",
  "It breathed hard, and a convulsive motion agitated its limbs.",
  "How can I describe my emotions at this catastrophe, or how delineate the wretch whom with such infinite pains and care I had endeavoured to form?",
];

async function durationMs(path) {
  const { stdout } = await run("ffprobe", ["-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", path]);
  return Number(stdout.trim()) * 1000;
}

const work = await mkdtemp(join(tmpdir(), "libratory-narrate-"));
const input = join(work, "passage.txt");
const wav = join(work, "passage.wav");
const chunks = join(work, "chunks");

// One sentence per line, so every chunk Kokoro emits belongs to exactly one of them
await writeFile(input, SENTENCES.join("\n"));
await run(join(REPO, ".venv/bin/python"), [
  join(REPO, "scripts/synthesize.py"),
  "--input", input, "--output", wav, "--voice", VOICE, "--chunks-dir", chunks,
], { env: { ...process.env, HF_HUB_OFFLINE: "1" } });

const manifest = JSON.parse(await readFile(join(chunks, "chunks.json"), "utf8"));
const files = (await readdir(chunks)).filter((f) => f.endsWith(".words.json")).sort();
if (files.length !== manifest.length) {
  throw new Error(`${manifest.length} chunks but ${files.length} with word timings — the voice dropped some`);
}

const cues = [];
let offset = 0;
let sentence = 0;
let consumed = "";

for (const [i, file] of files.entries()) {
  // A chunk is a whole sentence or part of one; the text tells us which sentence it belongs to
  consumed = `${consumed} ${manifest[i].text}`.trim();
  const tokens = JSON.parse(await readFile(join(chunks, file), "utf8"));
  let word = null;
  for (const token of tokens) {
    word ??= { text: "", a: token.startMs + offset, b: 0, s: sentence };
    word.text += token.text;
    word.b = token.endMs + offset;
    // Whitespace after a token is where one display word ends and the next begins
    if (/\s/.test(token.after)) {
      cues.push(word);
      word = null;
    } else {
      word.text += token.after;
    }
  }
  if (word) cues.push(word);
  offset += await durationMs(join(chunks, `chunk-${String(i + 1).padStart(3, "0")}.wav`));
  if (consumed === SENTENCES[sentence]) {
    sentence += 1;
    consumed = "";
  }
}

for (const [i, text] of SENTENCES.entries()) {
  const spoken = cues.filter((c) => c.s === i).map((c) => c.text).join(" ");
  if (spoken !== text) throw new Error(`sentence ${i} came back as ${JSON.stringify(spoken)}`);
}

await run("ffmpeg", ["-y", "-loglevel", "error", "-i", wav, "-ac", "1", "-c:a", "aac", "-b:a", "48k", "-movflags", "+faststart", AUDIO]);

const quote = (s) => JSON.stringify(s);
await writeFile(CUES, `// Generated by scripts/narrate.mjs — do not edit by hand.
export type Cue = [text: string, startMs: number, endMs: number, sentence: number];

export const AUDIO_SRC = "/${AUDIO.replace(/^public\//, "")}";

export const CUES: Cue[] = [
${cues.map((c) => `  [${quote(c.text)}, ${Math.round(c.a)}, ${Math.round(c.b)}, ${c.s}]`).join(",\n")}
];
`);

console.log(`${cues.length} words · ${(await durationMs(AUDIO) / 1000).toFixed(1)}s → ${AUDIO}, ${CUES}`);
